test: &test
  database: pg_party_<%= Rails.env %>
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: foobar123
  host: 127.0.0.1
  schema_search_path: e9651f34
  port: 5432
  pool: 50

development:
  <<: *test
